<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = DB::table('categories')->pluck('id', 'display_name')->toArray(); // Récupérer les IDs des categories

        DB::table('services')->insert([
            ['nom' => '69', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Anulingus (actif)', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Anulingus (passif)', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Branlette seins', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Café Pipe', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Champagne doré actif', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Champagne doré passif', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Couple', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Cunnilingus', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Doigté anal', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Doigté vaginal', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Domination soft', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Double pénétration', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Duo', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Ejaculation corps', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Ejaculation faciale', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Ejaculation multiple OK', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Facesitting', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Femme Fontaine', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Fessées Acceptées', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Fétichisme', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'French Kiss', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'GFE', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Gorge Profonde', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Jeux de rôles', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Lingerie', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Massage érotique', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Masturbation', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Porn Star Experience', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Rapport Sexuel', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Service VIP', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Sexe de groupe (orgie)', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Sex Toys', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Sodomie (active)', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Sodomie (passive)', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Soumise', 'categorie_id' => $categories['escort'] ?? null],
            ['nom' => 'Stripteas', 'categorie_id' => $categories['escort'] ?? null],

            ['nom' => 'Drainage lymphatique', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],
            ['nom' => 'Massage 4 mains', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],
            ['nom' => 'Massage 6 mains', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],
            ['nom' => 'Massage abdominal', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],
            ['nom' => 'Massage antistress', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],
            ['nom' => 'Massage Australien', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],
            ['nom' => 'Massage aux huiles', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],
            ['nom' => 'Massage ayurvédique', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],
            ['nom' => 'Massage body body', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],
            ['nom' => 'Massage californien', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],
            ['nom' => 'Massage douche', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],
            ['nom' => 'Massage en Couple', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],
            ['nom' => 'Massage Jacuzzi', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],
            ['nom' => 'Massage Naturiste', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],
            ['nom' => 'Massage oriental', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],
            ['nom' => 'Massage prostate', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],
            ['nom' => 'Massage Réciproque', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],
            ['nom' => 'Massage Shiatsu', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],
            ['nom' => 'Massage Suédois', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],
            ['nom' => 'Massage tantra', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],
            ['nom' => 'Massage thaïlandais', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],
            ['nom' => 'Séance Hydromassage', 'categorie_id' => $categories['masseuse-no-sex'] ?? null],

            ['nom' => 'Asphyxie érotique', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Ballbusting', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Bondage', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Camisoles', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Caviar actif', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Caviar passif', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Champagne doré actif', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Champagne doré passif', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Chantage', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Domination hard', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Electro stimulation', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Enfermement', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Etranglement', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Exhibition', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Facesitting', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Féminisation', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Fessée active', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Fessée passive', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Fétichisme', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Fisting actif', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Fisting passif', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Humiliations', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Jeux de bougie', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Jeux médicaux', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Jeux sexuels', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Lavement érotiques', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Piétinement', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Privation d’orgasme', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Rasage', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Scatophilie', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Soumise', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Suspensions', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Tortures érotiques', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Travestissement', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Urologie', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Viol théâtralisé', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],
            ['nom' => 'Voyeurisme', 'categorie_id' => $categories['dominatrice-bdsm'] ?? null],

            ['nom' => '69', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Anulingus (actif)', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Anulingus (passif)', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Branlette seins', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Café pipe', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Champagne doré actif', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Champagne doré passif', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Couple', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Domination soft', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Double pénétration', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Ejaculation corps', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Ejaculation faciale', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Facesitting', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Fellation', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Fétichisme', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'French Kiss', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'GFE', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Gorge profonde', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Jeux de rôles', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Lingerie', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Massage érotique', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Masturbation', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Porn Star Experience', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Rapport Sexuel', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Service VIP', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Sexe de Groupe (orgie)', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Sex Toys', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Sodomie (active)', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Sodomie (passive)', 'categorie_id' => $categories['trans'] ?? null],
            ['nom' => 'Striptease', 'categorie_id' => $categories['trans'] ?? null],         
        ]);
    }
}
